config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'

  get 'project/new'

  get 'projects/list'

  get 'project/view'

  get 'project/show'

  get 'project/edit'

  resources :projects
  root 'projects#index'

  resource :admin_session
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :title, presence: true
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :url, presence: true
	validates :email, presence: true
 	validates :description, presence: true
  	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'tom' && password == 'test'
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_filter :authenticate, :except => [:index, :show]

	def index 
		@projects = Project.order('last_name ASC')
	end

	def list 
		@projects = Project.order('last_name ASC')
	end


	def show
  		@project = Project.find params[:id]
  		render :layout => false
	end

	def new 
		 @project = Project.new
	end

	def create
	  @project = Project.new(params.require(:project).permit(:title, :first_name, :last_name, :url, :email, :vimeo_link, :description, :twitter, :quote))
	  if @project.save
	    flash[:notice] = "#{@project.title} saved."
	    redirect_to  :action => 'list'
	  else
	    render :new
	  end
	end

	def edit
  		@project = Project.find params[:id]
	end

	def update
	  @project = Project.find params[:id]
	  if @project.update_attributes(params.require(:project).permit(:title, :first_name, :last_name, :url, :email, :vimeo_link, :description, :twitter, :quote))
	    flash[:notice] = "#{@project.title} saved."
	    redirect_to  :action => 'list'
	  else
	    render :edit
	  end
	end

	def destroy
	  @project = Project.find (params[:id])
	  @project.destroy
	 redirect_to  :action => 'list'
	end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin_sessions/index.html.erb
<% title 'Login' %>
 
<% form_for @admin_session, :url => admin_session_path do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </p>
 
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
 
  <%= f.submit "Login" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XV | Goldsmiths Degree Show</title>
  <meta name="description" content="XV Show Goldsmith BA Design Degree Show 2015">
  <meta name="keywords" content="Goldsmiths, degree, design, show, 2015">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

</head>
<body>

<%= yield %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62839656-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/projects/edit.html.erb
<div class="background-white">

	<div class="backend-toolbar">

		<div class="backend-container">
			<%= link_to "Back To Site", projects_path %>
			<%= link_to "Add a Project", new_project_path %>
		</div>

	</div>

	<div class="backend-container">

		<div class="projects-holder">


		<%= simple_form_for (@project) do |form| %>
			  <%= form.input :title, label: "Project Title" %>
		  	  <%= form.input :first_name, label: "First Name" %>
		  	  <%= form.input :last_name, label: "Last Name" %>
		  	  <%= form.input :url, label: "Designer / Project Website", hint: "e.g facebook.com"  %>
		  	  <%= form.input :email, label: "Designers Email", hint: "tom@miln.co" %>
		  	  <%= form.input :vimeo_link, label: "Vimeo Link",  hint: "full address e.g: https://vimeo.com/99876106" %>
		  	  <%= form.input :twitter, label: "Twitter" %>
		  	  <%= form.input :description, label: "Description", as: :text, :input_html => {:rows => 10} %>
		  	  <%= form.input :quote, label: "Quote", as: :text, :input_html => {:rows => 2} %>
		  	  
		  	  <%= form.button :submit %>
		<% end %>

		<p>
		  <%= link_to 'Delete', project_path(@project), :method => :delete, :confirm => "Are you sure?" %>
		</p>

		</div>

	</div>

</div>

app/views/projects/index.html.erb
<header>

	<div class="layout-container">

		<nav class="main-menu">

			<ul class="menu-items">
				
				<li class="menu-item">

					<a id="layout-hero" class="menu-item-link  menu-underline js-about menu--item--active" href="">Info</a>

				</li>

				<li class="menu-item">
				
					<a id="layout-hero" class="menu-item-link  menu-underline js-manifesto" href="">Manifesto</a>

				</li>

				<li class="menu-item">

					<a id="layout-designers" class="menu-item-link js-people" href="">People</a>

				</li>
		
			</ul>

		</nav>

		<h1 class="header-logo-large">Goldsmiths BA Design Degree Show '15</h1>

	</div>

</header>

<article class="layout-hero">

	<div class="layout-container">

		<div class="layout-hero-one-column-grid">

			<div class="hero-type-block layout-clear-top article-info-block">

				<span class="event-date">Industry and Press </br> Private View </br> 5 June 6pm - 10pm </br></span>
				<span class="event-date">Public Opening </br> 6 June 10am - 7pm </br> 7 June 10am - 7pm </br> 8 June 10am - 4pm</span>
				<span class="event-details">The Old Truman Brewery </br> Ely’s Yard (F Block G4) </br> 15 Hanbury Street </br> E1 6QR</span>

				<%= link_to "@xvshow", 'https://twitter.com/xvshow?lang=en-gb', :class => "link-hero-twitter", :target => "_blank"%>
			</div>

			<div class="hero-type-block layout-clear-top article-manifesto-block">

				<p class="type-hero">Out there is a world filled with complexity and contradictions; built from infinite intertwining systems; where change is the only constant; where uncertainty is certain and defining is problematic.</p> <p class="type-hero">Here you will find a design practice which acknowledges, engages with, enjoys and acts upon the complexity of the world. Here you will navigate through fields of interrogation which intersect and then separate, which connect and then contradict. </p> <p class="type-hero">Our routes are not linear, our outcomes are not set in stone: we chart ourselves loosely on changeable scales. We are collected here, together, for now.</p>
			
			</div>

		</div>

		<div class="layout-three-column-grid layout-clear-top">


			<div class="image-hero-container">

				<%= image_tag image_path("xv_home_2.gif") %>
				
			</div>

			<nav class="article-data-list">

				<ul class="list-data-x">
					<h5 class="type-data-title">Download Maps</h5>
					<%= link_to "Slow - Fast / Past - Future", '/slow_fast_past_future2.pdf', :class => "link-switch-dataset", :target => "_blank"%>
					<%= link_to "Fiction - Reality / Artificial - Natural", '/fiction_reality_articial_natural2.pdf', :class => "link-switch-dataset", :target => "_blank"%>
					<%= link_to "Order - Chaos / Reality - Fiction", '/order_chaos_reality_fiction2.pdf', :class => "link-switch-dataset", :target => "_blank"%>
					<%= link_to "Close - Far / Private - Public", '/close_far_private_public2.pdf', :class => "link-switch-dataset", :target => "_blank"%>
				</ul>

			</nav>

		</div>

	</div>

</article>

<article class="layout-designers">

		<article class="layout-designer-expanded">

			<div class="layout-container">

				<a href="" class="link-back-to-all"></a>

				<div class="layout-two-column-grid">

					<div id="js_title" class="layout-title-holder">
										
						<h4 id="js_project_name" class="expanded-project-name"></h4>

						<a id="js_project_site" class="link-expanded-email"></a>

						<a id="js_project_email" class="link-expanded-email"></a>

						<a id="js_project_twitter" class="link-expanded-email"></a>

					</div>

					<div id="slider" class="swiper-container">

						<div class="swiper-wrapper">

							<div id="js-swipe-holder-one" class="swiper-slide"></div>
							<!-- <div id="js-swipe-holder-two" class="swiper-slide"></div>
	            			<div id="js-swipe-holder-three" class="swiper-slide"></div> -->
				        
				        </div>

						<!-- <div class="swiper-button-next"></div>
						<div class="swiper-button-prev"></div> -->

				</div>

			</div>

			<div class="layout-two-column-grid layout-column-right">

					<div class="layout-description-holder">

						<p id="js_quote" class="expanded-project-quote">
							
						</p>

						<div id="js_description" class="expanded-project-description">
							
						</div>

					</div>

				</div>

		</div>

	</div>

		

		</div>

		</article>

		<article class="layout-designer-list">

			<div class="layout-container">

			<div class="layout-one-column-grid">

				<ul class="list-all-designers">

					<% i = 0 %>
					<% @projects.limit(13).each do |project| %>
					<% i += 1%>

					<li name="<%= project.id %>">
						<span class="list-number">00<%= i %></span>
			  			<a class="list-designer-name"><%= project.first_name %> <%= project.last_name %></a>	
			  			<a class="list-project-name"><%= project.title %></a>		
			  		</li>

					<% end %>

				</ul>

			</div>

		</arcticle>

		<div class="layout-one-column-grid">

			<ul class="list-all-designers">

				<% i = 13 %>
				<% @projects.offset(13).limit(13).each do |project| %>
				<% i += 1%>

				<li name="<%= project.id %>">
					<span class="list-number">0<%= i %></span>
		  			<a class="list-designer-name"><%= project.first_name %> <%= project.last_name %></a>	
		  			<a class="list-project-name"><%= project.title %></a>		
			  	</li>

				<% end %>

			</ul>

		</div>

		<div class="layout-one-column-grid">

			<ul class="list-all-designers">

				<% i = 26 %>
				<% @projects.offset(26).limit(13).each do |project| %>
				<% i += 1%>

				<li name="<%= project.id %>">
					<span class="list-number">0<%= i %></span>
		  			<a class="list-designer-name"><%= project.first_name %> <%= project.last_name %></a>	
		  			<a class="list-project-name"><%= project.title %></a>		
			  	</li>

				<% end %>

			</ul>

		</div>

		<div class="layout-one-column-grid layout-column-right">

			<ul class="list-all-designers">

				<% i = 39 %>
				<% @projects.offset(39).limit(13).each do |project| %>
				<% i += 1%>

				<li name="<%= project.id %>">
					<span class="list-number">0<%= i %></span>
		  			<a class="list-designer-name"><%= project.first_name %> <%= project.last_name %></a>	
		  			<a class="list-project-name"><%= project.title %></a>
			  	</li>

				<% end %>

			</ul>

		</div>

		<ul>

	</div>

</div>

</article>

app/views/projects/list.html.erb
<div class="background-white">

	<div class="backend-toolbar">

		<div class="backend-container">
			<p><%= link_to "Back To Site", projects_path %></p>
			<p><%= link_to "Add a Project", new_project_path %></p>
		</div>

	</div>

	<div class="backend-container">

		<div class="projects-holder">

			<% for project in @projects do %>

			<div class="backend-project">

			  <h3 class="backend-project-link"><%= link_to project.title, edit_project_path(project.id) %></h3>
			  
			  <h4 class="backend-project-designer"><%= project.first_name %> <%= project.last_name %></h4>

			  <h4 class="backend-project-designer">ID: <%= project.id %></h4>

			</div>

			<% end %>

		</div>

	</div>

</div>

app/views/projects/new.html.erb
 <div class="background-white">

	<div class="backend-toolbar">

		<div class="backend-container">
			<%= link_to "Back To Site", projects_path %>
			<%= link_to "Add a Project", new_project_path %>
		</div>

	</div>

	<div class="backend-container">

		<div class="projects-holder">

		<%= simple_form_for @project do |form| %>
		  <%= form.input :title, label: "Project Title" %>
		  	  <%= form.input :first_name, label: "First Name" %>
		  	  <%= form.input :last_name, label: "Last Name" %>
		  	  <%= form.input :url, label: "Designer / Project Website", hint: "e.g facebook.com"  %>
		  	  <%= form.input :email, label: "Designers Email", hint: "tom@miln.co" %>
		  	  <%= form.input :vimeo_link, label: "Vimeo Link",  hint: "full address e.g: https://vimeo.com/99876106" %>
		  	  <%= form.input :twitter, label: "Twitter" %>
		  	  <%= form.input :description, label: "Description", as: :text, :input_html => {:rows => 10} %>
		  	  <%= form.input :quote, label: "Quote", as: :text, :input_html => {:rows => 2} %>
		  	  <%= form.button :submit %>
		<% end %>

		</div>

	</div>

</div>

app/views/projects/show.html.erb
<h4 id="js_project_name" class="expanded-project-name"><%= @project.title %> - <%= @project.first_name %> <%= @project.last_name %></h4>
<%= link_to "#{@project.url}", "http://#{@project.url}", :id => "js_project_email", :class => "link-expanded-email", :target => "_blank"%>
<%= link_to "#{@project.email}", "mailto:#{@project.email}?Subject=Great%20Project!", :id => "js_project_email", :class => "link-expanded-email", :target => "_blank"%>
<%= link_to "#{@project.twitter}", "https://twitter.com/#{@project.twitter}", :id => "js_project_email", :class => "link-expanded-email", :target => "_blank"%>
<div id="js_image_one" class="img_wrapper swiper-slide"><%= image_tag image_path("#{@project.id}.1.jpg"), :onload => "imgLoaded(this)" %></div>
<p id="js_quote" class="expanded-project-quote"><%= @project.quote %></p>
<div id="js_description" class="expanded-project-description"><%= simple_format(@project.description) %></div>